version: "3.5"

services:
  postgres:
    image: postgres:latest
    container_name: co_shop_core_db
    environment:
      POSTGRES_USER: buyer_2000
      POSTGRES_PASSWORD: Iwant20Bagles!
      POSTGRES_DB: co_shop_core_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: