SET search_path TO CO_SHOP;

INSERT INTO GROUPS (NAME, INVITE_CODE)
VALUES ('Skiweekend', 'SWK1234'),
       ('Büro Party', 'BPY5678'),
       ('Hackathon', 'HACK890'),
       ('Aare Böötle',  'AARE234');

INSERT INTO MEMBERS (DISPLAY_NAME)
VALUES ('Sarah Müller'),
       ('Michael Becker'),
       ('Lisa Schneider'),
       ('David Wagner'),
       ('Emma Fischer'),
       ('Jonas Weber'),
       ('Anna Kowalski'),
       ('Thomas Neumann'),
       ('Sophie Dubois'),
       ('Carlos Fernández');

INSERT INTO GROUP_MEMBERS (GROUP_ID, MEMBER_ID)
VALUES
(1, 1),
(1, 4),
(1, 5),
(1, 7),
(2, 2),
(2, 3),
(2, 6),
(2, 9),
(3, 1),
(3, 3),
(3, 8),
(3, 10),
(3, 4),
(4, 1),
(4, 6),
(4, 7),
(4, 8),
(4, 9),
(4, 10);

INSERT INTO PRODUCTS (NAME, UNIT)
VALUES ('Brot', 'Stück'),
       ('Milch', 'Liter'),
       ('Eier', 'Stück'),
       ('Hähnchenbrust', 'kg'),
       ('Hackfleisch', 'kg'),
       ('Lachsfilet', 'kg'),
       ('Bananen', 'kg'),
       ('Äpfel', 'kg'),
       ('Tomaten', 'kg'),
       ('Zwiebeln', 'kg'),
       ('Kartoffeln', 'kg'),
       ('Karotten', 'kg'),
       ('Spinat', 'Bund'),
       ('Paprika', 'kg'),
       ('Brokkoli', 'Stück'),
       ('Reis', 'kg'),
       ('Nudeln', 'Pack'),
       ('Olivenöl', 'Flasche'),
       ('Butter', 'Päckchen'),
       ('Käse', 'kg'),
       ('Joghurt', 'Becher'),
       ('Orangensaft', 'Liter'),
       ('Müsli', 'Pack'),
       ('Passierte Tomaten', 'Dose'),
       ('Schwarze Bohnen', 'Dose');


INSERT INTO ITEMS (NAME, DESCRIPTION, UNIT, FK_GROUP, FK_PRODUCT)
VALUES
('Brot', 'Vollkornbrot für die Familie', 'Stück', 1, 1),
('Milch', 'Frische Vollmilch, bio', 'Liter', 1, 2),
('Eier', 'Freiland-Eier', 'Stück', 1, 3),
('Hähnchen', 'Hähnchenbrustfilet ohne Knochen', 'kg', 1, 4),
('Bananen', 'Bio-Bananen', 'kg', 1, 7),
('Brot', 'Tägliches Brot für die WG', 'Stück', 2, 1),
('Milch', 'Milch für den Kühlschrank', 'Liter', 2, 2),
('Zwiebeln', 'Gelbe Zwiebeln zum Kochen', 'kg', 2, 10),
('Reis', 'Basmatireis für Mahlzeiten', 'kg', 2, 16),
('Öl', 'Natives Olivenöl extra', 'Flasche', 2, 18),
('Brot', 'Sandwichbrot fürs Büro', 'Stück', 3, 1),
('Eier', 'Eier fürs Mittagessen', 'Stück', 3, 3),
('Nudeln', 'Schnell zubereitete Pasta', 'Pack', 3, 17),
('Käse', 'Käse für Sandwiches', 'kg', 3, 20),
('Tomaten', 'Frische Tomaten für Sandwiches', 'kg', 3, 9),
('Milch', 'Milch in Großpackung', 'Liter', 4, 2),
('Hähnchen', 'Großbestellung Hähnchenbrust', 'kg', 4, 4),
('Äpfel', 'Saisonale Apfelsorten', 'kg', 4, 8),
('Kartoffeln', 'Kartoffeln vom Bauernhof', 'kg', 4, 11),
('Joghurt', 'Bio-Joghurtbecher', 'Becher', 4, 21),
('Bier', 'Noser Bier', 'Liter', 3, null);

INSERT INTO REQUESTS (FK_ITEM, FK_MEMBER, QUANTITY, FOR_EVERYONE)
VALUES
(1, 1, 2, true),
(1, 4, 2, true),
(2, 4, 3, true),
(3, 5, 2, false),
(4, 7, 2, true),
(5, 1, 3, false),
(6, 2, 1, true),
(7, 3, 2, true),
(8, 6, 2, false),
(9, 9, 1, true),
(10, 2, 1, true),
(11, 1, 3, false),
(12, 3, 1, true),
(13, 8, 2, false),
(14, 10, 1, true),
(15, 4, 2, false),
(16, 5, 10, true),
(17, 6, 5, true),
(18, 7, 8, false),
(19, 8, 15, true),
(20, 9, 12, false),
(21, 1, 2, false),
(21, 3, 3, false),
(21, 8, 1, false);